# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: codenuggets.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codenuggets.com" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title
# Build settings
markdown: kramdown
gems: [jekyll-paginate]
paginate: 10
#excerpt_separator: <!--more-->

defaults:
  -
    scope:
      path: "_posts/lintcode"
      type: "posts"
    values:
      breadcrumb: "Coding Interview / LintCode & LeetCode"